[package]
name = "proxide"
version = "0.1.0"
authors = ["Mikko Rantanen <jubjub@jubjubnest.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
h2 = "*"
http = "*"
bytes = "*"
log = "*"
simplelog = "*"
tokio = { version = "*", features = [ "full", "sync" ] }
snafu = "*"
futures = "*"
tui = { version = "*", default-features = false, features = [ "crossterm" ] }
crossterm = "*"
uuid = { version = "*", features = [ "v4" ] }
chrono = "*"
pest = "*"
pest_derive = "*"
