[package]
name = "proxide"
version = "0.1.0"
authors = ["Mikko Rantanen <jubjub@jubjubnest.net>"]
edition = "2018"
license = "GPL-3.0-only"
description = """
Proxide is a debugging proxy for capturing HTTP/2 and gRPC traffic.
"""
repository = "https://github.com/Rantanen/proxide"
readme = "README.md"
excldue = [ "/test" ]

[dependencies]
h2 = "*"
http = "*"
bytes = { version = "*", features = [ "serde" ] }
log = "*"
simplelog = "*"
tokio = { version = "*", features = [ "full", "sync" ] }
snafu = "*"
futures = "*"
tui = { version = "*", default-features = false, features = [ "crossterm" ] }
crossterm = "*"
uuid = { version = "*", features = [ "v4", "serde" ] }
chrono = { version = "*", features = ["serde"] }
clap = "*"
protofish = { version = "*" }
serde = { version = "*", features = ["derive"] }
http-serde = "*"
rmp-serde = "*"
lazy_static = "*"
