[package]
name = "proxide"
version = "0.1.0"
authors = ["Mikko Rantanen <jubjub@jubjubnest.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
h2 = "0.2.0-alpha.1"
tokio = "0.2.0-alpha.4"
http = "*"
bytes = "*"
log = "*"
env_logger = "*"
